# Generated by Django 3.2.6 on 2021-08-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordwolfroom',
            name='cur_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wordwolfroom',
            name='game_ended',
            field=models.BooleanField(default=False),
        ),
    ]
