# Generated by Django 3.2.6 on 2021-08-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210806_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordwolfroom',
            name='wolf',
            field=models.IntegerField(default=0),
        ),
    ]
